CREATE TABLE IF NOT EXISTS `#__zoo_zl_zoocart_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `state` int(11) NOT NULL,
  `net` float NOT NULL,
  `tax` float NOT NULL,
  `shipping` float NOT NULL,
  `weight` float NOT NULL,
  `payment` float NOT NULL,
  `discount` float NOT NULL DEFAULT 0,
  `shipping_tax` float NOT NULL,
  `payment_tax` float NOT NULL,
  `subtotal` float NOT NULL,
  `tax_total` float NOT NULL,
  `total` float NOT NULL,
  `currency` text NOT NULL,
  `shipping_address` text NOT NULL,
  `billing_address` text NOT NULL,
  `payment_method` varchar(255) NOT NULL,
  `shipping_method` text NOT NULL,
  `discount_info` text NOT NULL,
  `params` text NOT NULL,
  `created_on` datetime NOT NULL,
  `modified_on` datetime NOT NULL,
  `notes` text NOT NULL,
  `ip` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;